
#Variables common between all scripts and modules

SEQUENCES = './sequences/'

DELIMITER = " -|::|- "

EVENT_LIST = ['cowrie.session.connect',
            'cowrie.direct-tcpip.request',
            'cowrie.log.closed',
            'cowrie.client.version',
            'cowrie.session.file_upload',
            'cowrie.session.file_download',
            'cowrie.direct-tcpip.redirect',
            'cowrie.login.success',
            'cowrie.client.fingerprint',
            'cowrie.session.params',
            'cowrie.login.failed',
            'cowrie.command.success',
            'cowrie.client.kex',
            'cowrie.command.failed',
            'cowrie.client.size',
            'cowrie.tunnelproxy-tcpip.data',
            'cowrie.command.input',
            'cowrie.session.closed',
            'cowrie.direct-tcpip.tunnel',
            'cowrie.direct-tcpip.data']

COLUMNS = ['eventid',
           'dst_ip',
           'dst_port',
           'src_ip',
           'src_port',
           'message',
           'sensor',
           'timestamp',
           'session',
           'data',
           'id',
           'protocol',
           'version',
           'hassh',
           'hasshAlgorithms',
           'kexAlgs',
           'keyAlgs',
           'encCS',
           'macCS',
           'compCS',
           'langCS',
           'username',
           'password',
           'duration',
           'arch',
           'input',
           'ttylog',
           'size',
           'shasum',
           'duplicate',
           'name',
           'value',
           'outfile',
           'destfile',
           'fingerprint',
           'key',
           'type',
           'url',
           'width',
           'height']